spring:
  datasource:
    url: jdbc:mysql://localhost:12345/jwt_service  # connection link to database
    username: jwt_service_user
    password: 2017ylda0l3R
    driver-class-name: com.mysql.jdbc.Driver
  jpa:                         # jpa properties
    hibernate:
      ddl-auto: create-drop   # create and destroy the schema when the application stops
    show-sql: true            # when spring JPA performs a query, it should show in console
    properties:
      hibernate:
        format_sql: true
    database: mysql           # telling JPA that we are using mysql
    database-platform: org.hibernate.dialect.MySQLDialect
